apiVersion: v1
kind: Secret
metadata:
  name: kubric-agent-credentials
  namespace: kubric-system
  labels:
    {{- include "kubric-agent.labels" . | nindent 4 }}
type: Opaque
data:
  clusterToken: {{ .Values.agent.token | default "" | b64enc | quote }}
