apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepull-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imagepull-test
  template:
    metadata:
      labels:
        app: imagepull-test
    spec:
      containers:
        - name: imagepull-test
          image: kubric-registry/definitely-does-not-exist:v99.99.99
